### ISSUE TITLE
Setting up mediastack

### ISSUE THREAD

**Issue by Yakrel** [geekau/mediastack#18]
Hello there,
It's me again :). I successfully set up this project without VPN and a few other components, but after that, I'm really confused. There are so many things to configure. How do you handle it all? What's the best practice to set everything up? You've already made the folder structure for us, thank you for that :). After this, I'm really wondering how to set up other things. For example, is there a recommended order for setting up the apps? What should be the root folders for Sonarr, Radarr, etc.? Also, are there any other suggested settings we should be aware of?

**Comment by geekau** [comment]
The README documentation on the https://github.com/geekau/mediastack repo is a quick start guide, the main guide is located at:

- [https://MediaStack.Guide/](https://MediaStack.Guide/)

Its designed to go down each of the menus, then go across to the next menu, then down the menu list again.

So you've already done most of what's needed in the Home, Preparation, and Installation menus, and should now focus on the "[Configure Media Apps](https://mediastack.guide/configuration/qbittorrent/)" menu list.

The MediaStack.Guide is still in heavy construction, so some stuff my not be accurate, but you can use these guides also, which where eariler versions in the Synology User's Forum... same guide / info:

https://www.synoforum.com/resources/ultimate-starter-page-1-jellyfin-jellyseerr-nzbget-torrents-and-arr-media-library-stack.184/

https://www.synoforum.com/resources/ultimate-starter-page-2-jellyfin-jellyseerr-nzbget-torrents-and-arr-media-library-stack.185/

**Comment by Yakrel** [comment]
I did follow your guide up until Radarr's last section, I hope you update the rest in the future.

**Comment by geekau** [comment]
Have responded to this query
