### ISSUE TITLE
"Services" repeated

### ISSUE THREAD

**Issue by proxmoxdebbie** [geekau/mediastack#19]
"services" is repeated in the following blocks: gluetun, filebot, homarr, smtp in the min-vpn_single-yaml 
Also gluetun wiki link is outdated
Suggested to move "services:" out of gluetun block 

**Current**
`
###########################################################################
###########################################################################
networks:
  mediastack:
    name: mediastack
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET:?err}
        gateway: ${DOCKER_GATEWAY:?err}

###########################################################################
###########################################################################
##
##
##
###########################################################################
###########################################################################
services:
  gluetun:
`

**Proposed**
`
###########################################################################
###########################################################################
networks:
  mediastack:
    name: mediastack
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET:?err}
        gateway: ${DOCKER_GATEWAY:?err}
###########################################################################
###########################################################################
###########################################################################
###########################################################################
services:
###########################################################################
###########################################################################
##
##
##
###########################################################################
###########################################################################
  gluetun:
`

**Comment by geekau** [comment]
Thanks for picking this up, I've updated the link for the Gluetun wiki in all the relevant YAML files, and removed the surplus "service" definitions from both the "single-yaml" docker compose files.

I merged filebot, homarr, and smtp on last commit, appears I left the extra service statements during the migration.

Fixed with: https://github.com/geekau/mediastack/commit/0b20ff0bfd07dbf4ae4daaa4f30841eb153db9e7

Thanks for pickup.
