### ISSUE TITLE
Heimdall is missing the port config to allow local network i think

### ISSUE THREAD

**Issue by flipside101** [geekau/mediastack#7]
i may be very wrong as this is all new to me but i think the port config for Heimdall is missing ?

**Comment by geekau** [comment]
I think you are right - I'm still working on the build / documentation for this, so haven't fully completed the development / configuration.

The intent is people to be able to access their services from the Internet using the SWAG container, which has Nginx reverse proxy built in, so I still need to test when we use the port from the Heimdall image, or the SWAG image.

Heimdall has ports in the base image: https://docs.linuxserver.io/images/docker-heimdall

However when you deploy with SWAG, the manuals say to use ports on SWAG, and Heimdall is not allocated ports in Docker: https://docs.linuxserver.io/general/swag#using-heimdall-as-the-home-page-at-domain-root

The later config is what I'm aiming for, and then we need to integrate Authelia into the same Nginx configs.

I'll keep this open until we get to it, but if you want to have a play with the settings on the last config, any feedback would help.

NOTE: This is the full guide I'm working towards, with Cloudflare Zero Trust / Authelia / Nginx Reverse Proxy, self hosting so its security accessible from the Internet - Heimdall should sit behind all this.

**Comment by flipside101** [comment]
looks like im gfrowung with you :)  ive got the base setup with qbitorrent through VPN , sonarr, sabnzb etc , oh and i added prowler to the VPN as well as a number of the nicer torrent sites are blocked in the UK so this allows access

**Comment by geekau** [comment]
Forgot to add link: https://www.linuxserver.io/blog/zero-trust-hosting-and-reverse-proxy-via-cloudflare-swag-and-authelia

This is the full guide I'm working towards, with Cloudflare Zero Trust / Authelia / Nginx Reverse Proxy, self hosting so its security accessible from the Internet - Heimdall should sit behind all this.

**Comment by riourik** [comment]
did it's already ready to worked? if I follow it and adapted it to full stack vpn ?

**Comment by Strux-DK** [comment]
Hi @geekau is this a project you're still working on?

**Comment by geekau** [comment]
> Hi @geekau is this a project you're still working on?

Unfortunately had too many things on earlier, however I'm back on this project now, and have done a major rewrite of the docker YAML files, and also added Plex and Homepage into the stack, then user get an option on this media players and application dashboards they want to run.

Have also added some network architectural diagrams to the Project's README.md file, so people can see how the network flows work for both Full VPN and Minimum VPN configurations.

**Comment by geekau** [comment]
Have resolved the missing port on Heimdall configuration, and also added Homepage as alternate landing page.
