### ISSUE TITLE
MediaStack guide empty

### ISSUE THREAD

**Issue by MasonNight** [geekau/mediastack#8]
I saw that the link didn't seem to contain any information, and that the link to your old guide was removed. Does this mean the old guide is outdated now?

**Comment by geekau** [comment]
Sorry, I've moved some of the build steps while I work on the web documentation.

While I'm working on updating the documentation, use the following guides as starters:

https://www.synoforum.com/resources/ultimate-starter-page-1-jellyfin-jellyseerr-nzbget-torrents-and-arr-media-library-stack.184/

https://www.synoforum.com/resources/ultimate-starter-page-2-jellyfin-jellyseerr-nzbget-torrents-and-arr-media-library-stack.185/

I'll leave open until we get the documentation onto the new site.

**Comment by eshtee** [comment]
Hello @geekau,
Thanks for the effort you have put into this. I just got it working on my Windows server. Was wondering if there is anything I can help with, like documentation etc.

Cheers,

**Comment by riourik** [comment]
hi @geekau Good job I would like know if you will do a guide for it I try it worked good but I reinstalled it with a vpn I cannot connect on it anymore so if you could do a how to will be awesome. thanks

**Comment by rc4l** [comment]
The guide is wildly out of date. It talks about Transmission which is defined nowhere @geekau

**Comment by dartworth** [comment]
> The guide is wildly out of date. It talks about Transmission which is defined nowhere @geekau No explanation of why we need Authelia, etc

@rc4l do you recommend a guide?

**Comment by Invinsk** [comment]
> Sorry, I've moved some of the build steps while I work on the web documentation.
> 
> While I'm working on updating the documentation, use the following guides as starters:
> 
> https://www.synoforum.com/resources/ultimate-starter-page-1-jellyfin-jellyseerr-nzbget-torrents-and-arr-media-library-stack.184/
> 
> https://www.synoforum.com/resources/ultimate-starter-page-2-jellyfin-jellyseerr-nzbget-torrents-and-arr-media-library-stack.185/
> 
> I'll leave open until we get the documentation onto the new site.

Hi, is there an up-to-date version of the guide?

**Comment by martyp187** [comment]
Given the linked guides are out of date..

Can someone confirm what the correct default download folder for BitTorrent is meant to be?

Some reference /data/torrents others /data/finished

**Comment by ninjanerdbgm** [comment]
I managed to get this stack up and running using the out of date guides and modifying as I go, but I can't figure out any reverse proxy settings or how to set up authelia, ddns-updater, flaresolverr, swag, tdarr, or unpackerr. Does anyone have any good guides for these?

**Comment by Vothm** [comment]
> I managed to get this stack up and running using the out of date guides and modifying as I go, but I can't figure out any reverse proxy settings or how to set up authelia, ddns-updater, flaresolverr, swag, tdarr, or unpackerr. Does anyone have any good guides for these?

Hi, for some reason i'm getting a "required variable DOCKER_SUBNET" is missing a value: err even though it's already defined. I have also tried making the subnet through docker network create command and still nothing. Did you have to do anything special for the docker subnet?

**Comment by ninjanerdbgm** [comment]
> > I managed to get this stack up and running using the out of date guides and modifying as I go, but I can't figure out any reverse proxy settings or how to set up authelia, ddns-updater, flaresolverr, swag, tdarr, or unpackerr. Does anyone have any good guides for these?
> 
> Hi, for some reason i'm getting a "required variable DOCKER_SUBNET" is missing a value: err even though it's already defined. I have also tried making the subnet through docker network create command and still nothing. Did you have to do anything special for the docker subnet?

Make sure you're including your .env file when you run docker compose. For example: `docker compose -f docker-compose-media-stack.yaml --env-file docker-compose.env up -d`

**Comment by geekau** [comment]
This is the latest development commit of the MediaStack.Guide:

https://25cbdf96.mediastack-guide.pages.dev/

Unfortunately I didn't realise just how much effort was needed to write all the documentation, and the amount of additional applications and integration also grew, it became an insurmountable task.

This dev guide is missing a lot of text / sections, but has all. The steps needed to get all the apps up and running, and all configured (except for SWAG, Authelia, and Heimdal).

**Comment by geekau** [comment]
Have done a major rewrite of the README.md files in the repo, they now have network architecture and a lot more technical info to get everyone running.

https://github.com/geekau/mediastack

I have also published content I have to the website, and will start improving it over the coming weeks.

https://MediaStack.Guide

If you have time and would like to help with the documentation, jump over to:

https://github.com/geekau/mediastack-guide
